name: PARICHAY
favicon: null
layout_spectrum: 0
typography_spectrum: 0.61019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#4c62b1'
    - '#d7d7d7'
    - '#ea282e'
    - '#ed8a35'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
