name: PARICHAY
favicon: null
layout_spectrum: 0.93567
typography_spectrum: 0.34565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00467a'
    - '#fefefe'
    - '#9f9c9c'
    - '#754a4e'
  brandStrength: 0
  lightness: 0.35715973749756813
  saturation: 0.19159541209228337
  rhythmicContrast: 0.011878245510160923
purpose: []
