name: PARICHAY
favicon: null
layout_spectrum: 0.63184
typography_spectrum: 0.43327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#4c62b1'
    - '#d7d7d7'
    - '#ea282e'
    - '#ed8a35'
  brandStrength: 0.9375
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
